//Vehicle summary Request actions
export const SEARCH_VEHICLESUMMARY_REQUEST = "SEARCH_VEHICLESUMMARY_REQUEST";
export const SEARCH_VEHICLESUMMARY_SUCCESS = "SEARCH_VEHICLESUMMARY_SUCCESS"
export const SEARCH_VEHICLESUMMARY_SUCCESS_EMPTY = "SEARCH_VEHICLESUMMARY_SUCCESS_EMPTY"
export const SEARCH_VEHICLESUMMARY_FAILURE = "SEARCH_VEHICLESUMMARY_FAILURE"
export const SEARCH_WITH_MODEL = "SEARCH_WITH_MODEL"